# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

# Site settings
title: 21st Century Weather resource monitoring
email: pgregory@unimelb.edu.au
#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://github.com/21centuryweather/nci_resource_tools" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
