name: Generate NCI resources report
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  runcode:
    runs-on: ubuntu-latest
    steps:
      - name: Run  
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USER}}
          key: ${{secrets.SSH_KEY}}
          passphrase: ${{secrets.PASSPHRASE}} 
          command_timeout: 60m
          script: |
              module use /g/data3/xp65/public/modules
              module load conda/analysis3
              cd /g/data/gb02/public/code/nci_resource_tools
              git remove docs/.ipynb_checkpoints/dashboard-checkpoint.html
	      git remove notebooks/dashboard.ipynb
              git notebooks/dashboard_files/figure-html/cell-10-output-1.png
              git pull
              source ./env.sh
              quarto render docs/dashboard.ipynb --execute --to html
              git add docs/dashboard*
              git commit -m "UPDATE: dashboard"
              quarto render docs/page.ipynb --execute --to html
              git add docs/page*
              git commit -m "UPDATE: page"
              git push
               
      
